---
ID: "7a022894-98e5-429c-aa6b-7a3c82e9cafb"
Parent: "df85e3d3-05f5-4bfa-b64a-f48f0c55ba52"
Template: "df85e3d3-05f5-4bfa-b64a-f48f0c55ba52"
Path: /sitecore/templates/ClothingCo/_Banner/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200304T140555Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8bdbaae1-70d6-461f-a79a-69d634595d85"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200304T140555Z
