---
ID: "8e4bb262-9604-4b88-ba27-54a825c10035"
Parent: "06eef10f-df02-4daf-b4c2-d17b22f08a40"
Template: "06eef10f-df02-4daf-b4c2-d17b22f08a40"
Path: /sitecore/templates/ClothingCo/Content Page/__Standard Values
DB: master
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200304T141121Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dec2dc8d-16a6-40d1-ad18-c9260db4ff19"
    - ID: "b7cbec9a-d1d9-4a26-bbd8-aada9ecd4260"
      Hint: Primary Content Text
      Value: Welcome to the Clothing Company. Take a look around. Check out our Blogs, Reviews, and Capsule Wardrobe offerings.
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200608T132258Z
